# Development Environment Configuration
# Reference: https://huggingface.co/learn/llm-course/chapter3/1

# Model Configuration
model:
  name: "meta-llama/Llama-3.1-8B-Instruct"
  max_length: 2048
  temperature: 0.7
  top_p: 0.9

# Training Configuration
training:
  batch_size: 4
  learning_rate: 2e-4
  num_epochs: 3
  warmup_steps: 100
  weight_decay: 0.01
  gradient_accumulation_steps: 4

# LoRA Configuration
lora:
  rank: 16
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

# Data Configuration
data:
  max_samples: 1000  # For development
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Logging
logging:
  level: "INFO"
  log_dir: "logs"
  save_steps: 100
  eval_steps: 200
